apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: open-match
    component: frontend
    release: open-match
  name: om-frontend
  namespace: open-match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match
      component: frontend
      release: open-match
  template:
    metadata:
      labels:
        app: open-match
        component: frontend
        release: open-match
    spec:
      containers:
        - image: registry.cn-beijing.aliyuncs.com/chrisliu95/frontend-multi-clusters:5-28-0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 51507
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: om-frontend
          ports:
            - containerPort: 51507
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz?readiness=true
              port: 51507
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: open-match
    component: frontend
    release: open-match
  name: om-frontend
  namespace: open-match
spec:
  ports:
    - name: http
      port: 51507
      protocol: TCP
      targetPort: 51507
  selector:
    app: open-match
    component: om-frontend
  type: ClusterIP