apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: flappy-bird
  namespace: default
spec:
  replicas: 3
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  gameServerTemplate:
    spec:
      containers:
        - image: registry.cn-beijing.aliyuncs.com/chrisliu95/flappy-bird:0.1
          name: flappy-bird
  network:
    networkType: AlibabaCloud-SLB
    networkConf:
      - name: SlbIds
        value: lb-bp1rkdcvity6ya2r6lnhv # fill in your slb id
      - name: PortProtocols
        value: 8000/TCP